[project]
author = "Matt York"
name = "netbox-scripts"
version = "0.1.0"
description = "A set of python scripts to interact with NetBox"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "tabulate==0.9.0",
]
